<?php
 $title = 'Availability';
 $this->headTitle($title);
 ?>
 <h3><?php echo $this->escapeHtml($title); ?></h3>
 <?php $flashMessage = $this->flashMessenger()->getMessages();
    if (count($flashMessage)) :
        foreach ($flashMessage as $msg) : 
            foreach ($msg as $type => $message) :
 ?>
    <span class="<?php echo $type; ?>"><?php echo $message; ?></span>
 <?php endforeach; ?>
 <?php endforeach; ?>
 </br></br>
<?php endif; ?>
 <div>
 <?php
 $flashMessage = $this->flashMessenger()->getMessages();
 $form->setAttribute('action', $this->url('book', array('action' => 'checkavailability')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('Name'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 echo "<a href='/book/public/book' class='float-right margin-topn30'>Back</a>";
 ?>
 </div>

 <div class="container margin-leftn20">
 <table class="table" width="100%">
    <thead>
      <tr>
        <th width="10%">Book ID</th>
        <th width="20%">Name</th>
        <th width="70%">Description</th>
        <th width="10%">Status</th>
      </tr>
    </thead>
    <tbody>
        <?php foreach ($books as $book) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($book->id);?></td>
                <td><?php echo $this->escapeHtml($book->name);?></td>
                <td><?php echo $this->escapeHtml($book->description);?></td>
                <td><?php echo $this->escapeHtml($book->status);?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
  </table>
  </div>