<div>
    <div class="alert-success alert" id="success"></div>
    <div class="alert-warning alert" id="error"></div>
    <?php
        echo $this->form()->openTag($form);
        echo '<div class="form-group col-sm-4">';
        echo $this->formRow($form->get('Name'));
        echo '</div>';
        echo $this->formRow($form->get('issue'));
        echo $this->formRow($form->get('return'));
        echo $this->formRow($form->get('availability'));
        echo $this->form()->closeTag();
    ?>
</div>
<div class="ajax-loader" id="loading-image">
    <img src='/book/public/img/loading.gif' width='250'/>
</div>
<div class="container margin-leftn15" id="bookList">
    <div class="align-center"><h3>Book Library</h3></div>
    <table class="table" width="100%">
        <thead>
            <tr>
                <th width="10%">Book ID</th>
                <th width="20%">Name</th>
                <th width="60%">Description</th>
                <th width="10%">Status</th>
            </tr>
        </thead>
        <tbody>
        <?php if( !empty($books) ) { foreach ($books as $book) { ?>
            <tr>
                <td><?php echo $this->escapeHtml($book->id);?></td>
                <td><?php echo $this->escapeHtml($book->name);?></td>
                <td><?php echo $this->escapeHtml($book->description);?></td>
                <td><?php echo $this->escapeHtml($book->status);?></td>
            </tr>
        <?php } }else { ?>
            <tr>
                <td colspan="4">No Records Found</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>