<div>
    <div class="margin-top10">
        <input class="btn btn-primary issue" type="button" value="Issue">
        <input class="btn btn-primary return" type="button" value="Return">
        <input class="btn btn-primary availability" type="button" value="Check Availability">
    </div>
</div>
<br>
<div class="container margin-leftn15">
    <div class="align-center"><h3>Book Library</h3></div>
    <table class="table" width="100%">
        <thead>
            <tr>
                <th width="10%">Book ID</th>
                <th width="20%">Name</th>
                <th width="60%">Description</th>
                <th width="10%">Status</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($books as $book) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($book->id);?></td>
                <td><?php echo $this->escapeHtml($book->name);?></td>
                <td><?php echo $this->escapeHtml($book->description);?></td>
                <td><?php echo $this->escapeHtml($book->status);?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>